"""initial governed platform schema

Revision ID: 48f2772be5c4
Revises:
Create Date: 2026-07-23 23:30:40.034842
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '48f2772be5c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('run_id', sa.String(length=48), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_run_id'), ['run_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('run_id', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)

    op.create_table('break_glass_grants',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('scope', sa.String(length=160), nullable=False),
    sa.Column('incident_id', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('break_glass_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_break_glass_grants_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_break_glass_grants_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_break_glass_grants_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_break_glass_grants_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_break_glass_grants_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_break_glass_grants_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_break_glass_grants_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('change_proposals',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('component_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('confidence_percent', sa.Integer(), nullable=False),
    sa.Column('evidence_completeness_percent', sa.Integer(), nullable=False),
    sa.Column('affected_runs', sa.Integer(), nullable=False),
    sa.Column('affected_controls_json', sa.JSON(), nullable=False),
    sa.Column('expected_risk_reduction_percent', sa.Integer(), nullable=False),
    sa.Column('source_refs_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('proposed_diff_json', sa.JSON(), nullable=False),
    sa.Column('evaluation_plan_json', sa.JSON(), nullable=False),
    sa.Column('required_approvals_json', sa.JSON(), nullable=False),
    sa.Column('rollout_plan_json', sa.JSON(), nullable=False),
    sa.Column('rollback_plan', sa.Text(), nullable=False),
    sa.Column('decision_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_proposals_component_type'), ['component_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_proposals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_proposals_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_change_proposals_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_proposals_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_proposals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_proposals_updated_at'), ['updated_at'], unique=False)

    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chunks_document_id'), ['document_id'], unique=False)

    op.create_table('control_lifecycles',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('control_lifecycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_lifecycles_kind'), ['kind'], unique=True)
        batch_op.create_index(batch_op.f('ix_control_lifecycles_status'), ['status'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('segment', sa.String(length=80), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_subject_requests',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('subject_key', sa.String(length=80), nullable=False),
    sa.Column('subject_ref', sa.String(length=80), nullable=False),
    sa.Column('jurisdiction', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('systems_json', sa.JSON(), nullable=False),
    sa.Column('export_digest', sa.String(length=64), nullable=True),
    sa.Column('correction_summary', sa.Text(), nullable=False),
    sa.Column('restriction_scope', sa.Text(), nullable=False),
    sa.Column('deletion_summary', sa.Text(), nullable=False),
    sa.Column('proof_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_subject_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_subject_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_requests_subject_key'), ['subject_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_requests_subject_ref'), ['subject_ref'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('risk_label', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_title'), ['title'], unique=False)

    op.create_table('enterprise_idempotency_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('route', sa.String(length=160), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enterprise_idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enterprise_idempotency_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_enterprise_idempotency_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('enterprise_outbox_events',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('aggregate_id', sa.String(length=120), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enterprise_outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enterprise_outbox_events_aggregate_id'), ['aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enterprise_outbox_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_enterprise_outbox_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_enterprise_outbox_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_enterprise_outbox_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('governance_imports',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('filename', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('rows_json', sa.JSON(), nullable=False),
    sa.Column('errors_json', sa.JSON(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('governance_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governance_imports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_governance_imports_status'), ['status'], unique=False)

    op.create_table('governance_records',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_import_id', sa.String(length=48), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('governance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governance_records_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_governance_records_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_governance_records_source_import_id'), ['source_import_id'], unique=False)

    op.create_table('identity_access_decisions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('auth_method', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('assurance_level', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=False),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('checks_json', sa.JSON(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('claims_digest', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identity_access_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_access_decisions_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_access_decisions_assurance_level'), ['assurance_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_access_decisions_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_access_decisions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_access_decisions_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_access_decisions_payload_digest'), ['payload_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_access_decisions_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_access_decisions_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_access_decisions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('integration_deliveries',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('approval_id', sa.String(length=48), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('response_digest', sa.String(length=64), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('approval_id', name='uq_integration_delivery_approval')
    )
    with op.batch_alter_table('integration_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_deliveries_approval_id'), ['approval_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_deliveries_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_deliveries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_deliveries_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_deliveries_payload_digest'), ['payload_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_deliveries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_deliveries_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_deliveries_updated_at'), ['updated_at'], unique=False)

    op.create_table('knowledge_changes',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('source_id', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('proposed_claims_json', sa.JSON(), nullable=False),
    sa.Column('contradictions_json', sa.JSON(), nullable=False),
    sa.Column('affected_runs', sa.Integer(), nullable=False),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_changes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_changes_risk'), ['risk'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_changes_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_changes_status'), ['status'], unique=False)

    op.create_table('knowledge_claims',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('source_id', sa.String(length=48), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('normalized', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('source_excerpt', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=False),
    sa.Column('review_due', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_claims_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_claims_review_due'), ['review_due'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_claims_risk'), ['risk'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_claims_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_claims_status'), ['status'], unique=False)

    op.create_table('knowledge_connector_files',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('connector_id', sa.String(length=48), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=48), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('obsidian_uri', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('links_json', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_connector_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_connector_files_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_connector_files_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_connector_files_relative_path'), ['relative_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_connector_files_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_connector_files_status'), ['status'], unique=False)

    op.create_table('knowledge_connectors',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('vault_name', sa.String(length=160), nullable=False),
    sa.Column('vault_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('include_folders_json', sa.JSON(), nullable=False),
    sa.Column('required_tags_json', sa.JSON(), nullable=False),
    sa.Column('default_owner', sa.String(length=120), nullable=False),
    sa.Column('classification', sa.String(length=40), nullable=False),
    sa.Column('review_days', sa.Integer(), nullable=False),
    sa.Column('last_scan_digest', sa.String(length=64), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_connectors_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_connectors_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_connectors_status'), ['status'], unique=False)

    op.create_table('knowledge_releases',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=48), nullable=False),
    sa.Column('change_id', sa.String(length=48), nullable=False),
    sa.Column('claims_added', sa.Integer(), nullable=False),
    sa.Column('contradictions_resolved', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=False),
    sa.Column('integrity_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_releases_change_id'), ['change_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_releases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_releases_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_releases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_releases_version'), ['version'], unique=True)

    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('review_due', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_sources_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_content_hash'), ['content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_review_due'), ['review_due'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_title'), ['title'], unique=False)

    op.create_table('knowledge_sync_previews',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('connector_id', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('scan_digest', sa.String(length=64), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=False),
    sa.Column('skipped_json', sa.JSON(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('applied_by', sa.String(length=120), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_sync_previews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_sync_previews_connector_id'), ['connector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sync_previews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sync_previews_scan_digest'), ['scan_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sync_previews_status'), ['status'], unique=False)

    op.create_table('lifecycle_incidents',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('agent_id', sa.String(length=48), nullable=False),
    sa.Column('run_id', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lifecycle_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lifecycle_incidents_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lifecycle_incidents_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lifecycle_incidents_status'), ['status'], unique=False)

    op.create_table('lifecycle_policy_changes',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('agent_id', sa.String(length=48), nullable=False),
    sa.Column('incident_id', sa.String(length=48), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('candidate_policy', sa.String(length=40), nullable=False),
    sa.Column('replay_summary_json', sa.JSON(), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lifecycle_policy_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lifecycle_policy_changes_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lifecycle_policy_changes_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lifecycle_policy_changes_status'), ['status'], unique=False)

    op.create_table('managed_agents',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('scopes_json', sa.JSON(), nullable=False),
    sa.Column('evaluation_score', sa.Integer(), nullable=True),
    sa.Column('cycle_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('managed_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_agents_status'), ['status'], unique=False)

    op.create_table('secure_contexts',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('content_digest', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=160), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('classification', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('model_access', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=48), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secure_contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secure_contexts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_secure_contexts_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_secure_contexts_owner'), ['owner'], unique=False)
        batch_op.create_index(batch_op.f('ix_secure_contexts_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secure_contexts_scope'), ['scope'], unique=False)
        batch_op.create_index(batch_op.f('ix_secure_contexts_status'), ['status'], unique=False)

    op.create_table('security_twin_simulations',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('scenario_id', sa.String(length=80), nullable=False),
    sa.Column('scenario_name', sa.String(length=200), nullable=False),
    sa.Column('candidate_profile', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('nodes_json', sa.JSON(), nullable=False),
    sa.Column('edges_json', sa.JSON(), nullable=False),
    sa.Column('steps_json', sa.JSON(), nullable=False),
    sa.Column('controls_json', sa.JSON(), nullable=False),
    sa.Column('blast_radius_json', sa.JSON(), nullable=False),
    sa.Column('containment_plan_json', sa.JSON(), nullable=False),
    sa.Column('containment_decision_json', sa.JSON(), nullable=False),
    sa.Column('verification_json', sa.JSON(), nullable=False),
    sa.Column('evidence_digest', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_twin_simulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_twin_simulations_candidate_profile'), ['candidate_profile'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_twin_simulations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_twin_simulations_evidence_digest'), ['evidence_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_twin_simulations_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_twin_simulations_scenario_id'), ['scenario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_twin_simulations_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_twin_simulations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_twin_simulations_updated_at'), ['updated_at'], unique=False)

    op.create_table('trust_approvals',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('tenant_id', sa.String(length=120), nullable=False),
    sa.Column('requester_subject', sa.String(length=160), nullable=False),
    sa.Column('approver_subject', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource', sa.String(length=200), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('payload_digest', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('required_assurance', sa.String(length=40), nullable=False),
    sa.Column('decision_comment', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trust_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_approvals_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_approvals_approver_subject'), ['approver_subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_approvals_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_approvals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_approvals_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_approvals_payload_digest'), ['payload_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_approvals_requester_subject'), ['requester_subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_approvals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_approvals_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trust_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_approvals_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_trust_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_trust_approvals_requester_subject'))
        batch_op.drop_index(batch_op.f('ix_trust_approvals_payload_digest'))
        batch_op.drop_index(batch_op.f('ix_trust_approvals_expires_at'))
        batch_op.drop_index(batch_op.f('ix_trust_approvals_created_at'))
        batch_op.drop_index(batch_op.f('ix_trust_approvals_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_trust_approvals_approver_subject'))
        batch_op.drop_index(batch_op.f('ix_trust_approvals_action'))

    op.drop_table('trust_approvals')
    with op.batch_alter_table('security_twin_simulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_twin_simulations_updated_at'))
        batch_op.drop_index(batch_op.f('ix_security_twin_simulations_status'))
        batch_op.drop_index(batch_op.f('ix_security_twin_simulations_severity'))
        batch_op.drop_index(batch_op.f('ix_security_twin_simulations_scenario_id'))
        batch_op.drop_index(batch_op.f('ix_security_twin_simulations_outcome'))
        batch_op.drop_index(batch_op.f('ix_security_twin_simulations_evidence_digest'))
        batch_op.drop_index(batch_op.f('ix_security_twin_simulations_created_at'))
        batch_op.drop_index(batch_op.f('ix_security_twin_simulations_candidate_profile'))

    op.drop_table('security_twin_simulations')
    with op.batch_alter_table('secure_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secure_contexts_status'))
        batch_op.drop_index(batch_op.f('ix_secure_contexts_scope'))
        batch_op.drop_index(batch_op.f('ix_secure_contexts_run_id'))
        batch_op.drop_index(batch_op.f('ix_secure_contexts_owner'))
        batch_op.drop_index(batch_op.f('ix_secure_contexts_expires_at'))
        batch_op.drop_index(batch_op.f('ix_secure_contexts_created_at'))

    op.drop_table('secure_contexts')
    with op.batch_alter_table('managed_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managed_agents_status'))

    op.drop_table('managed_agents')
    with op.batch_alter_table('lifecycle_policy_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lifecycle_policy_changes_status'))
        batch_op.drop_index(batch_op.f('ix_lifecycle_policy_changes_incident_id'))
        batch_op.drop_index(batch_op.f('ix_lifecycle_policy_changes_agent_id'))

    op.drop_table('lifecycle_policy_changes')
    with op.batch_alter_table('lifecycle_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lifecycle_incidents_status'))
        batch_op.drop_index(batch_op.f('ix_lifecycle_incidents_run_id'))
        batch_op.drop_index(batch_op.f('ix_lifecycle_incidents_agent_id'))

    op.drop_table('lifecycle_incidents')
    with op.batch_alter_table('knowledge_sync_previews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_sync_previews_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sync_previews_scan_digest'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sync_previews_created_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sync_previews_connector_id'))

    op.drop_table('knowledge_sync_previews')
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_title'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_review_due'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_owner'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_created_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_content_hash'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_classification'))

    op.drop_table('knowledge_sources')
    with op.batch_alter_table('knowledge_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_releases_version'))
        batch_op.drop_index(batch_op.f('ix_knowledge_releases_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_releases_source_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_releases_created_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_releases_change_id'))

    op.drop_table('knowledge_releases')
    with op.batch_alter_table('knowledge_connectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_connectors_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_connectors_kind'))
        batch_op.drop_index(batch_op.f('ix_knowledge_connectors_created_at'))

    op.drop_table('knowledge_connectors')
    with op.batch_alter_table('knowledge_connector_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_connector_files_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_connector_files_source_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_connector_files_relative_path'))
        batch_op.drop_index(batch_op.f('ix_knowledge_connector_files_content_hash'))
        batch_op.drop_index(batch_op.f('ix_knowledge_connector_files_connector_id'))

    op.drop_table('knowledge_connector_files')
    with op.batch_alter_table('knowledge_claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_claims_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_claims_source_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_claims_risk'))
        batch_op.drop_index(batch_op.f('ix_knowledge_claims_review_due'))
        batch_op.drop_index(batch_op.f('ix_knowledge_claims_owner'))

    op.drop_table('knowledge_claims')
    with op.batch_alter_table('knowledge_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_changes_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_changes_source_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_changes_risk'))
        batch_op.drop_index(batch_op.f('ix_knowledge_changes_created_at'))

    op.drop_table('knowledge_changes')
    with op.batch_alter_table('integration_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_deliveries_updated_at'))
        batch_op.drop_index(batch_op.f('ix_integration_deliveries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_integration_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_integration_deliveries_payload_digest'))
        batch_op.drop_index(batch_op.f('ix_integration_deliveries_mode'))
        batch_op.drop_index(batch_op.f('ix_integration_deliveries_created_at'))
        batch_op.drop_index(batch_op.f('ix_integration_deliveries_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_integration_deliveries_approval_id'))

    op.drop_table('integration_deliveries')
    with op.batch_alter_table('identity_access_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_access_decisions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_identity_access_decisions_subject'))
        batch_op.drop_index(batch_op.f('ix_identity_access_decisions_role'))
        batch_op.drop_index(batch_op.f('ix_identity_access_decisions_payload_digest'))
        batch_op.drop_index(batch_op.f('ix_identity_access_decisions_decision'))
        batch_op.drop_index(batch_op.f('ix_identity_access_decisions_created_at'))
        batch_op.drop_index(batch_op.f('ix_identity_access_decisions_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_identity_access_decisions_assurance_level'))
        batch_op.drop_index(batch_op.f('ix_identity_access_decisions_action'))

    op.drop_table('identity_access_decisions')
    with op.batch_alter_table('governance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_records_source_import_id'))
        batch_op.drop_index(batch_op.f('ix_governance_records_external_id'))
        batch_op.drop_index(batch_op.f('ix_governance_records_category'))

    op.drop_table('governance_records')
    with op.batch_alter_table('governance_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_imports_status'))
        batch_op.drop_index(batch_op.f('ix_governance_imports_created_at'))

    op.drop_table('governance_imports')
    with op.batch_alter_table('enterprise_outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enterprise_outbox_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_enterprise_outbox_events_status'))
        batch_op.drop_index(batch_op.f('ix_enterprise_outbox_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_enterprise_outbox_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_enterprise_outbox_events_aggregate_id'))

    op.drop_table('enterprise_outbox_events')
    with op.batch_alter_table('enterprise_idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enterprise_idempotency_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_enterprise_idempotency_records_created_at'))

    op.drop_table('enterprise_idempotency_records')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_title'))

    op.drop_table('documents')
    with op.batch_alter_table('data_subject_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_subject_ref'))
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_subject_key'))
        batch_op.drop_index(batch_op.f('ix_data_subject_requests_status'))

    op.drop_table('data_subject_requests')
    op.drop_table('customers')
    with op.batch_alter_table('control_lifecycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_lifecycles_status'))
        batch_op.drop_index(batch_op.f('ix_control_lifecycles_kind'))

    op.drop_table('control_lifecycles')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_document_id'))

    op.drop_table('chunks')
    with op.batch_alter_table('change_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_proposals_updated_at'))
        batch_op.drop_index(batch_op.f('ix_change_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_change_proposals_source_type'))
        batch_op.drop_index(batch_op.f('ix_change_proposals_severity'))
        batch_op.drop_index(batch_op.f('ix_change_proposals_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_change_proposals_created_at'))
        batch_op.drop_index(batch_op.f('ix_change_proposals_component_type'))

    op.drop_table('change_proposals')
    with op.batch_alter_table('break_glass_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_break_glass_grants_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_break_glass_grants_subject'))
        batch_op.drop_index(batch_op.f('ix_break_glass_grants_status'))
        batch_op.drop_index(batch_op.f('ix_break_glass_grants_incident_id'))
        batch_op.drop_index(batch_op.f('ix_break_glass_grants_expires_at'))
        batch_op.drop_index(batch_op.f('ix_break_glass_grants_created_at'))
        batch_op.drop_index(batch_op.f('ix_break_glass_grants_correlation_id'))

    op.drop_table('break_glass_grants')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_decision'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_run_id'))

    op.drop_table('approvals')
    op.drop_table('accounts')
    # ### end Alembic commands ###
